Update F5 gene to Pypgx
sbslee/pypgx pull request #39
Opened 2021-12-13 17:46 UTC by NTNguyen13

Hi, I found that currently Pypgx does not have some genes in PharmGKB guideline, so I want to contribute my effort into this great open-source package. I start with a 'simple' gene first: F5 only have 1 variant in [PGKB](https://www.pharmgkb.org/chemical/PA452637/guidelineAnnotation/PA166104955), and it's a Level 1A.

As I worked on this, I found that this variant is not quite simple. The gene F5 strand has been flipped when moving up from GRCh37 to GRCh38, which makes a quite confusing case. The guideline states that the risk allele is T, but it was the reference allele in GRCh37. This was changed in GRCh38, into C as the reference allele.

I'm afraid that it may lead to some changes in representation of the diplotype: for example, for homozygous of risk allele TT in GRCh37, no variant will be called => Reference/Reference, while in GRCh38, this variant will be called, and represented as c.1601G>A/c.1601G>A diplotype.

What do you think about this case? I'm making this draft pull request so that we can discuss directly on it.

P/s: Do you have any plan to expand to MT-RNR1 gene, it also level 1A and newly published on CPIC: https://cpicpgx.org/guidelines/cpic-guideline-for-aminoglycosides-and-mt-rnr1/

2021-12-14 03:21 UTC, sbslee commented
@NTNguyen13,

Thanks for this PR! Before I do a thorough review, I want to point out few things:

1. It was very wise of you to start with a simple gene :) By the end of this exercise, I hope we can establish some basic expectations when it comes to the addition of a new gene.
2. "The gene F5 strand has been flipped when moving up from GRCh37 to GRCh38" -> I just checked, and please note that this is not the case. The gene is encoded in the minus strand for both GRCh37 and GRCh38. I think what you are referring to is change in reference allele at the SNP level between GRCh37 and GRCh38, which is actually quite common for PGx genes. For example, if you look at the `variant-table.csv` file, you will find many variants that have different values in the `GRCh37Allele` and `GRCh38Allele` columns (e.g. rs1809810 in CYP2A6 where GRCh37 has 19-41350664-A-T while GRCh38 has 19-40844759-T-A).
3. Note that this does NOT affect diplotype representation because star allele definition in PyPGx already accounts for this discrepancy. For example, if you look at the `GRCh37Default` and `GRCh38Default` columns in the `gene-table.csv` file, you will see that GRCh37 is CYP2D6\*2 as while GRCh38 is CYP2D6\*1. This is because the GRCh37 haplotype already contains two variants that define the CYP2D6\*2 allele; therefore, if an individual does not have any CYP2D6 variants and the sequence reads were aligned against GRCh37, we know the individual is homozygous for CYP2D6\*2/\*2. You can also see this in action from the `allele-table.csv` file:
 ```
 >>> import pypgx
 >>> pypgx.list_variants('CYP2D6', alleles=['*2'], assembly='GRCh37')
 []
 >>> pypgx.list_variants('CYP2D6', alleles=['*2'], assembly='GRCh38')
 ['22-42126611-C-G', '22-42127941-G-A']
 ```
4. I didn't have immediate plans for adding new genes for a while, but I'd be more than happy to review any PRs that include addition of new genes. However, there are many moving parts when it comes to the addition of a new gene, so to minimize any potential errors, I will only review one gene at a time.

I will review this PR soon!

2021-12-14 06:07 UTC, sbslee requested changes
Thanks for the PR! I know how much tedious things can get when adding a new gene to PyPGx, so great job getting this much done already in your first attempt :) Please look at my suggested changes.

Once this PR is merged, there are some additional steps to be taken. For example, we need to add reference haplotype panel from the 1000 Genomes Project for F5 for both GRCh37 and GRCh38. However, these are things that I need to take care because I have the original VCF files downloaded.

2021-12-14 06:07 UTC, sbslee commented on CHANGELOG.rst
> +* Update data for F5
Please use:
```suggestion
* Add new gene: F5.
```

2021-12-14 06:07 UTC, sbslee commented on docs/genes.rst
> +====
Please make sure to have no hanging `=`:
```suggestion
F5
==
```

2021-12-14 06:07 UTC, sbslee commented on docs/genes.rst
> +--------------------------
Please make sure to have no hanging `=`:
```suggestion
Phenotype summary for F5
------------------------
```

2021-12-14 06:07 UTC, sbslee commented on docs/genes.rst
> +      - Reference/c.1601G>A
Please use "Leiden" instead of "c.1601G>A":
```suggestion
      - Reference/Leiden
```

Also, please add PharmGKB reference:

```
Resources for F5
----------------

- `Annotation of DPWG Guideline for hormonal contraceptives for systemic use and F5 <https://www.pharmgkb.org/chemical/PA452637/guidelineAnnotation/PA166104955>`__
```

2021-12-14 06:07 UTC, sbslee commented on pypgx/api/data/diplotype-table.csv
> +F5,c.1601G>A/c.1601G>A,Unfavorable Response
Please use the following:

```suggestion
F5,Reference/Reference,Favorable Response
F5,Reference/Leiden,Unfavorable Response
F5,Leiden/Leiden,Unfavorable Response
```

2021-12-14 06:07 UTC, sbslee commented on pypgx/api/data/gene-table.csv
> +F5,TRUE,FALSE,N/A,TRUE,FALSE,Diplotype,N/A,N/A,Reference,Reference,Reference,-,chr1:169481189-169555826,chr1:169511951-169586588,"169481189,169484682,169487650,169489758,169492435,169493039,169494075
1. I'm not sure where you got the gene information, but I always get mine (RefSeq) from UCSC Genome Browser > Tools > Table Browser > `group: Genes and Gene Predictions`, `track: NCBI RefSeq`. The results look like this for GRCh37:
 ```
 #bin	name	chrom	strand	txStart	txEnd	cdsStart	cdsEnd	exonCount	exonStarts	exonEnds	score	name2	cdsStartStat	cdsEndStat	exonFrames
 1878	NM_000130.5	chr1	-	169481188	169555719	169483550	169555624	25	169481188,169484681,169487649,169489757,169492434,169493038,169494074,169495138,169497152,169498845,169500023,169505743,169509531,169513533,169515679,169519038,169519877,169521794,169524419,169525883,169528390,169529791,169541458,169551668,169555466,	169483697,169484864,169487801,169489902,169492590,169493142,169494146,169495255,169497332,169499056,169500260,169505918,169512352,169513746,169515830,169519253,169519977,169521972,169524585,169526105,169528534,169530004,169541581,169551760,169555719,	0	F5	cmpl	cmpl	0,0,1,0,0,1,1,1,1,0,0,2,1,1,0,1,0,2,1,1,1,1,1,2,0,
 ```
2. Note that the name of transcript is NM_000130.5. This RefSeq only has 25 exons, not 52 exons as in your data.
3. For `GRCh37Region`	and `GRCh38Region` I usually add +/- 3 kb to capture regulatory elements. Also, please don't add the 'chr' string.
4. GRCh37 sequence already has the Leiden variant, so `GRCh37Default` should be "Leiden" instead of "Reference".
5. Strings in the `ExonStarts` and `ExonEnds` columns should have a comma (,) at the end.

Please use the following:

```suggestion
F5,TRUE,FALSE,N/A,TRUE,FALSE,Diplotype,N/A,N/A,Reference,Leiden,Reference,-,1:169478188-169558719,1:169508950-169589481,"169481188,169484681,169487649,169489757,169492434,169493038,169494074,169495138,169497152,169498845,169500023,169505743,169509531,169513533,169515679,169519038,169519877,169521794,169524419,169525883,169528390,169529791,169541458,169551668,169555466,","169483697,169484864,169487801,169489902,169492590,169493142,169494146,169495255,169497332,169499056,169500260,169505918,169512352,169513746,169515830,169519253,169519977,169521972,169524585,169526105,169528534,169530004,169541581,169551760,169555719,","169511950,169515443,169518411,169520519,169523196,169523800,169524836,169525900,169527914,169529607,169530785,169536505,169540293,169544295,169546441,169549800,169550639,169552556,169555181,169556645,169559152,169560553,169572220,169582430,169586228,","169514459,169515626,169518563,169520664,169523352,169523904,169524908,169526017,169528094,169529818,169531022,169536680,169543114,169544508,169546592,169550015,169550739,169552734,169555347,169556867,169559296,169560766,169572343,169582522,169586481,"
```

2021-12-14 06:07 UTC, sbslee commented on pypgx/api/data/phenotype-table.csv
> +F5,Indeterminate,Normal Risk
1. I removed `Indeterminate` because we don't have that phenotype in the updated `diplotype-table.csv` file.
2. I changed "Normal Risk" and "High Risk" to "None" because these values must be directly from CPIC and F5 is not in CPIC yet (see [CACNA1S consult text and implementation workflow](https://api.pharmgkb.org/v1/download/file/attachment/CACNA1S_consult_text_and_implementation_workflow_post.xlsx) as an example).

Please use the following:

```suggestion
F5,Favorable Response,None
F5,Unfavorable Response,None
```

2021-12-14 06:07 UTC, sbslee commented on pypgx/api/data/variant-table.csv
> +F5,1-169519049-T-C,1-169549811-C-T,rs6025,1,169519049,169549811,T,C,R534Q,N/A,N/A
1. I added the `GRCh38Synonym` column because it was missing.
2. The `Variant` column should be a nucleotide sequence, not a protein change.
3. "R534Q" should be used for the "Impact" column.
4. Finally, please move the variant after the DPYD gene to keep the alphabetical order.

Please use the following:

```suggestion
F5,1-169519049-T-C,1-169549811-C-T,rs6025,1,169519049,169549811,T,C,T,R534Q,N/A,N/A
```

2021-12-14 06:07 UTC, sbslee commented on pypgx/api/data/allele-table.csv
> +F5,c.1601G>A,N/A,Unknown Function,1-169519049-T-C,N/A,1-169549811-C-T,N/A,FALSE
Please use:

```suggestion
F5,Reference,N/A,Normal Function,1-169519049-T-C,N/A,N/A,N/A,FALSE
F5,Leiden,N/A,Unknown Function,N/A,N/A,1-169549811-C-T,N/A,FALSE
```

2021-12-14 06:52 UTC, NTNguyen13 commented on pypgx/api/data/gene-table.csv
> +F5,TRUE,FALSE,N/A,TRUE,FALSE,Diplotype,N/A,N/A,Reference,Reference,Reference,-,chr1:169481189-169555826,chr1:169511951-169586588,"169481189,169484682,169487650,169489758,169492435,169493039,169494075
Hi, I forgot to add that I get mine information from gencode38. However I believe that consistency is important, I will use RefSeq UCSC next time I query exon information.

2021-12-14 07:10 UTC, sbslee approved these changes
Everything looks good! Merging this PR.

2021-12-14 07:11 UTC, merged

2021-12-15 00:17 UTC, sbslee commented
@NTNguyen13, just letting you know that I added reference haplotype panel for F5 (983abee)! Now you should be able to genotype F5 with PyPGx :)